import org.gradle.api.tasks.compile.JavaCompile
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile

buildscript {
    ext {
        // main
        app_compile_sdk_version = 35
        app_target_sdk_version = 35
        app_min_sdk_version = 21
        tv_min_sdk_version = 23

        mobile_version_code = 70
        mobile_version_name = "2.14.0_RC2"

        tv_version_code = 5
        tv_version_name = "1.2.1"

        // java
        jvm_toolchain_version = 17
        jvm_bytecode_version = 11
    }
}

plugins {
    alias libs.plugins.android.application apply false
    alias libs.plugins.android.library apply false
    alias libs.plugins.kotlin.android apply false
    alias libs.plugins.kotlin.jvm apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias libs.plugins.ksp apply false
    alias(libs.plugins.detekt) apply false
    alias(libs.plugins.ktlint) apply false
    alias libs.plugins.gms apply false
    alias libs.plugins.appmetrica apply false
    alias(libs.plugins.version.catalog.update)
}

// todo delete after fixes in conscrypt library
allprojects {
    if (libs.versions.conscrypt.android.get() == "2.5.3") {
        throw new Exception("Do not use conscrypt version 2.5.3, it's broken")
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}

def analyzeDependencyProjects = [
    project(":app-tv"),
    project(":data"),
    project(":shared-android-ktx"),
    project(":shared-app"),
    project(":quill-di"),
    project(":shared-ktx"),
]

configure(analyzeDependencyProjects) { Project moduleProject ->
    tasks.withType(KotlinJvmCompile).configureEach {
        compilerOptions.jvmTarget.set(JvmTarget.fromTarget(jvm_bytecode_version.toString()))
    }

    tasks.withType(JavaCompile).configureEach {
        sourceCompatibility = jvm_bytecode_version.toString()
        targetCompatibility = jvm_bytecode_version.toString()
    }

    pluginManager.withPlugin("com.android.application") {
        moduleProject.extensions.configure("android") { androidExtension ->
            androidExtension.compileOptions {
                sourceCompatibility = JavaVersion.toVersion(jvm_bytecode_version)
                targetCompatibility = JavaVersion.toVersion(jvm_bytecode_version)
            }
        }
    }

    pluginManager.withPlugin("com.android.library") {
        moduleProject.extensions.configure("android") { androidExtension ->
            androidExtension.compileOptions {
                sourceCompatibility = JavaVersion.toVersion(jvm_bytecode_version)
                targetCompatibility = JavaVersion.toVersion(jvm_bytecode_version)
            }
        }
    }
}
