build:
  maxIssues: 0

complexity:
  active: false

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  InjectDispatcher:
    active: false
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true

empty-blocks:
  active: false

exceptions:
  active: false

naming:
  active: false

performance:
  active: false

potential-bugs:
  active: true
  AvoidReferentialEquality:
    active: true
  CastNullableToNonNullableType:
    active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true
  UnreachableCode:
    active: true

comments:
  active: false

style:
  active: true
  ForbiddenImport:
    active: true
    imports:
      - "kotlinx.coroutines.GlobalScope"
      - "kotlinx.coroutines.runBlocking"
    excludes:
      - "**/SuggestionsContentProvider.kt"
      - "**/AniLibertyAuthInterceptor.kt"
      - "**/UnauthorizedInterceptor.kt"
      - "**/ApiConfig.kt"
      - "**/AppCookieJar.kt"
      - "**/CoilLibriaImageLoaderImpl.kt"
