plugins {
    alias libs.plugins.kotlin.jvm
}

kotlin {
    jvmToolchain(jvm_toolchain_version)
}

dependencies {
    implementation libs.kotlin.stdlib
    implementation libs.kotlin.coroutines.core

    testImplementation "junit:junit:4.13.2"
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.1"
}
